desc = "Tools to help build a consistent API across various packages, use it, and enquire about it"
keywords = ["package", "module", "API"]
license = "MIT"
name = "ModuleInterfaceTools"
uuid = "5cb8414e-7aab-5a03-a681-351269c074bf"
repo = "https://github.com/JuliaString/ModuleInterfaceTools.jl.git"
