name = "ModuleInterfaceTools"
uuid = "57012a8c-f217-493e-9761-d906ce7698cb"
keywords = ["package", "module", "API"]
license = "MIT"
desc = "Tools to help build a consistent API across various packages, use it, and enquire about it"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
version = "0.1.3"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
