desc = "Tools to help build a consistent API across various packages, use it, and enquire about it"
keywords = ["package", "module", "API"]
license = "MIT"
name = "ModuleInterfaceTools"
deps = ["Test"]
git-tree-sha1 = "b4fc455cbdc313ecd8c08173153bf8abfcb9e5a6"
repo = "https://github.com/JuliaString/ModuleInterfaceTools.jl.git"
repo-rev = ""
repo-url = "/s/ModuleInterfaceTools.jl"
uuid = "5cb8414e-7aab-5a03-a681-351269c074bf"
version = "0.1.0+"
